# Generated by Django 4.0 on 2022-01-17 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 17, 18, 43, 46, 238315)),
        ),
    ]
